databases:
  - name: urlshortener
    databaseName: urlshortener
    user: urlshortener

services:
  - type: web
    name: urlshortener
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn urlshortener.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshortener
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
