# Generated by Django 4.1.2 on 2022-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_longtoshort_chrome_longtoshort_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='others',
            field=models.IntegerField(default=0),
        ),
    ]
